# Site settings
title: Il blog di MM
email: ilblogdimm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Il blog di MM è una bandiera al vento. Parla di ambiente, musica...e anche un po' di tutto il resto.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "ilblogdimm.it" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

paginate: 3
paginate_path: "page:num"

ordine:
  Ambiente: 2
  MusicalMente: 3
  Divagando: 4
