# Site settings
title: Il blog di MM
email: marco.minoggio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Il blog di MM è una bandiera al vento. Parla di ambiente, musica...e anche un po' di tutto il resto.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ilblogdimm

# Build settings
markdown: kramdown
